//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class pc
    {
        public string pc_id { get; set; }
        public string os { get; set; }
        public string cpu { get; set; }
        public string ram { get; set; }
        public string hdd { get; set; }
    
        public virtual item item { get; set; }
    }
}
