//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class require_history
    {
        public string staff_id { get; set; }
        public string item_id { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public byte[] date { get; set; }
    
        public virtual item item { get; set; }
        public virtual staff staff { get; set; }
    }
}
