//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_history_type
    {
        public int asset_history_type_id { get; set; }
        public string type_code { get; set; }
        public string type_description { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
