//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        public int asset_id { get; set; }
        public Nullable<int> os_id { get; set; }
        public Nullable<int> asset_type_id { get; set; }
        public Nullable<int> original_supplier_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> using_by_staff_id { get; set; }
        public string asset_code { get; set; }
        public string brand { get; set; }
        public Nullable<decimal> price { get; set; }
        public string cpu { get; set; }
        public string ram { get; set; }
        public string hdd { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> start_date_warranty { get; set; }
        public Nullable<System.DateTime> expiry_date_warranty { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
