//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class assetEntities : DbContext
    {
        public assetEntities()
            : base("name=assetEntities")
        {
        }

        internal void Dispose()
        {
            throw new NotImplementedException();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asset> asset { get; set; }
        public virtual DbSet<asset_history> asset_history { get; set; }
        public virtual DbSet<asset_history_type> asset_history_type { get; set; }
        public virtual DbSet<asset_type> asset_type { get; set; }
        public virtual DbSet<history> history { get; set; }
        public virtual DbSet<os> os { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user_login> user_login { get; set; }
    }
}
