//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_history
    {
        public int asset_history_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> asset_id { get; set; }
        public Nullable<int> asset_history_type { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> history_timestamp { get; set; }
    }
}
