//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradITAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_history_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asset_history_type()
        {
            this.asset_history = new HashSet<asset_history>();
        }
    
        public int asset_history_type_id { get; set; }
        public string type_code { get; set; }
        public string type_description { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asset_history> asset_history { get; set; }
    }
}
